<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="..\..\src\BpmSoftSync.Adapters.BpmSoft\BpmSoftSync.Adapters.BpmSoft.csproj" /><ProjectReference Include="..\BpmSoftSync.Testing\BpmSoftSync.Testing.csproj" /></ItemGroup></Project>
