<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="..\BpmSoftSync.Domain\BpmSoftSync.Domain.csproj" /><ProjectReference Include="..\BpmSoftSync.Application\BpmSoftSync.Application.csproj" /><ProjectReference Include="..\BpmSoftSync.Adapters.BpmSoft\BpmSoftSync.Adapters.BpmSoft.csproj" /></ItemGroup></Project>
